dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install codecov
script:
  - coverage run --source flowio --omit="flowio/tests/*" run_tests.py

after_success:
  - codecov
  
branches:
  only: 
    - master
