name: Test (master)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: whitews/FlowIO/.github/workflows/test_base.yml@master
    secrets: inherit